version: 2

mkdocs: {}  # tell readthedocs to use mkdocs

python:
  version: 3.7
  install:
  - method: pip
    path: .
  - requirements: docs/.readthedocs-requirements.txt

x-custom-steps:
  - pydoc-markdown --build --site-dir $SITE_DIR -vv docs/pydoc-markdown.yml
