#!/usr/bin/env python3

import elasticsearch_kibana_cli

debug=True
# ping_connection=False
# kbn_version='faux-version'
ping_connection=True
kbn_version=None

if __name__ == '__main__':
    elasticsearch_kibana_cli.ElasticsearchKibanaCLI(
        ping_connection=ping_connection,
        kbn_version=kbn_version,
        debug=debug
    ).main()
